-- Bridge: upstream lifecycle tables skipped by FromGram timestamp versions.
-- account freeze notifications, suggested posts, channel gift notification jobs.

-- === from 0131_account_freeze_visibility.up.sql ===
-- A freeze/unfreeze is a viewer-visible user projection change. Version the
-- durable fact so a claimed old nudge can never acknowledge a newer state.
ALTER TABLE public.account_restrictions
  ADD COLUMN IF NOT EXISTS version bigint DEFAULT 1 NOT NULL;
ALTER TABLE public.account_restrictions
  DROP CONSTRAINT IF EXISTS account_restrictions_version_check,
  ADD CONSTRAINT account_restrictions_version_check CHECK (version > 0);

-- updateUser has no pts. This coalesced queue is only a crash-safe online
-- nudge; offline clients reconstruct the current restriction from the
-- authoritative account_restrictions row during normal user hydration.
CREATE TABLE IF NOT EXISTS public.account_freeze_notifications (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  target_user_id bigint NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  frozen_user_id bigint NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  version bigint NOT NULL,
  frozen boolean NOT NULL,
  status text DEFAULT 'pending' NOT NULL,
  attempts integer DEFAULT 0 NOT NULL,
  next_attempt_at timestamp with time zone DEFAULT now() NOT NULL,
  lease_until timestamp with time zone,
  last_error text DEFAULT '' NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT account_freeze_notifications_status_check
    CHECK (status IN ('pending', 'dispatching', 'delivered')),
  CONSTRAINT account_freeze_notifications_attempts_check CHECK (attempts >= 0),
  CONSTRAINT account_freeze_notifications_version_check CHECK (version > 0),
  CONSTRAINT account_freeze_notifications_not_self_check CHECK (target_user_id <> frozen_user_id),
  UNIQUE (target_user_id, frozen_user_id)
);

CREATE INDEX IF NOT EXISTS account_freeze_notifications_ready_idx
  ON public.account_freeze_notifications(next_attempt_at, id)
  WHERE status = 'pending';

CREATE INDEX IF NOT EXISTS account_freeze_notifications_lease_idx
  ON public.account_freeze_notifications(lease_until, id)
  WHERE status = 'dispatching';

-- === from 0133_suggested_post_lifecycle.up.sql ===
-- Durable suggested-post approval/payment/publication state.  The row is the
-- idempotency key for a monoforum suggestion; message/update rows remain the
-- client-visible source of truth and are written in the same transaction.
CREATE TABLE IF NOT EXISTS public.suggested_post_approvals (
    monoforum_id bigint NOT NULL,
    suggestion_message_id integer NOT NULL,
    parent_channel_id bigint NOT NULL,
    actor_user_id bigint NOT NULL,
    payer_user_id bigint NOT NULL,
    state text NOT NULL,
    price_kind text NOT NULL DEFAULT '',
    price_amount bigint NOT NULL DEFAULT 0,
    price_nanos integer NOT NULL DEFAULT 0,
    schedule_date integer NOT NULL DEFAULT 0,
    approval_service_message_id integer NOT NULL DEFAULT 0,
    published_message_id integer NOT NULL DEFAULT 0,
    settlement_due integer NOT NULL DEFAULT 0,
    final_service_message_id integer NOT NULL DEFAULT 0,
    created_at integer NOT NULL,
    updated_at integer NOT NULL,
    PRIMARY KEY (monoforum_id, suggestion_message_id),
    CONSTRAINT suggested_post_approvals_shape_check CHECK (
        monoforum_id>0 AND suggestion_message_id>0 AND parent_channel_id>0 AND
        actor_user_id>0 AND payer_user_id>0 AND created_at>0 AND updated_at>=created_at AND
        state IN ('balance_low','rejected','scheduled','published','completed','refunded') AND
        price_kind IN ('','stars','ton') AND price_amount>=0 AND price_nanos BETWEEN 0 AND 999999999 AND
        ((price_kind='' AND price_amount=0 AND price_nanos=0) OR
         (price_kind='stars' AND price_amount>0) OR
         (price_kind='ton' AND price_amount>0 AND price_nanos=0)) AND
        schedule_date>=0 AND approval_service_message_id>=0 AND published_message_id>=0 AND
        settlement_due>=0 AND final_service_message_id>=0)
);

CREATE INDEX IF NOT EXISTS suggested_post_approvals_schedule_idx
    ON public.suggested_post_approvals(schedule_date,monoforum_id,suggestion_message_id)
    WHERE state='scheduled';
CREATE INDEX IF NOT EXISTS suggested_post_approvals_settlement_idx
    ON public.suggested_post_approvals(settlement_due,monoforum_id,suggestion_message_id)
    WHERE state='published';

-- === from 0134_suggested_post_effective_publish_date.up.sql ===
-- TDesktop omits schedule_date for "Publish Now", while the approval action
-- renderer always formats an absolute publication date.  Backfill rows written
-- by the initial lifecycle implementation and keep current/history/difference
-- projections on the same effective timestamp.
UPDATE channel_messages m
SET suggested_post = jsonb_set(
        m.suggested_post,
        '{ScheduleDate}',
        to_jsonb(a.created_at),
        true
    )
FROM suggested_post_approvals a
WHERE a.schedule_date = 0
  AND a.state IN ('scheduled', 'published', 'completed', 'refunded')
  AND m.channel_id = a.monoforum_id
  AND m.id = a.suggestion_message_id
  AND COALESCE((m.suggested_post->>'Accepted')::boolean, false)
  AND COALESCE((m.suggested_post->>'ScheduleDate')::integer, 0) = 0;

UPDATE channel_messages m
SET action = jsonb_set(
        m.action,
        '{SuggestedPostScheduleDate}',
        to_jsonb(a.created_at),
        true
    )
FROM suggested_post_approvals a
WHERE a.schedule_date = 0
  AND a.state IN ('scheduled', 'published', 'completed', 'refunded')
  AND m.channel_id = a.monoforum_id
  AND m.id = a.approval_service_message_id
  AND m.action->>'Type' = 'suggested_post_approval'
  AND NOT COALESCE((m.action->>'SuggestedPostRejected')::boolean, false)
  AND NOT COALESCE((m.action->>'SuggestedPostBalanceTooLow')::boolean, false)
  AND COALESCE((m.action->>'SuggestedPostScheduleDate')::integer, 0) = 0;

UPDATE channel_update_events e
SET payload = jsonb_set(
        e.payload,
        '{message,SuggestedPost,ScheduleDate}',
        to_jsonb(a.created_at),
        true
    )
FROM suggested_post_approvals a
WHERE a.schedule_date = 0
  AND a.state IN ('scheduled', 'published', 'completed', 'refunded')
  AND e.channel_id = a.monoforum_id
  AND e.message_id = a.suggestion_message_id
  AND e.event_type = 'edit_channel_message'
  AND COALESCE((e.payload #>> '{message,SuggestedPost,Accepted}')::boolean, false)
  AND COALESCE((e.payload #>> '{message,SuggestedPost,ScheduleDate}')::integer, 0) = 0;

UPDATE channel_update_events e
SET payload = jsonb_set(
        e.payload,
        '{message,Action,SuggestedPostScheduleDate}',
        to_jsonb(a.created_at),
        true
    )
FROM suggested_post_approvals a
WHERE a.schedule_date = 0
  AND a.state IN ('scheduled', 'published', 'completed', 'refunded')
  AND e.channel_id = a.monoforum_id
  AND e.message_id = a.approval_service_message_id
  AND e.event_type = 'new_channel_message'
  AND e.payload #>> '{message,Action,Type}' = 'suggested_post_approval'
  AND NOT COALESCE((e.payload #>> '{message,Action,SuggestedPostRejected}')::boolean, false)
  AND NOT COALESCE((e.payload #>> '{message,Action,SuggestedPostBalanceTooLow}')::boolean, false)
  AND COALESCE((e.payload #>> '{message,Action,SuggestedPostScheduleDate}')::integer, 0) = 0;

UPDATE suggested_post_approvals
SET schedule_date = created_at,
    updated_at = GREATEST(updated_at, created_at)
WHERE schedule_date = 0
  AND state IN ('scheduled', 'published', 'completed', 'refunded');

ALTER TABLE suggested_post_approvals
    DROP CONSTRAINT IF EXISTS suggested_post_approvals_shape_check;

ALTER TABLE suggested_post_approvals
    ADD CONSTRAINT suggested_post_approvals_shape_check CHECK (
        monoforum_id>0 AND suggestion_message_id>0 AND parent_channel_id>0 AND
        actor_user_id>0 AND payer_user_id>0 AND created_at>0 AND updated_at>=created_at AND
        state IN ('balance_low','rejected','scheduled','published','completed','refunded') AND
        price_kind IN ('','stars','ton') AND price_amount>=0 AND price_nanos BETWEEN 0 AND 999999999 AND
        ((price_kind='' AND price_amount=0 AND price_nanos=0) OR
         (price_kind='stars' AND price_amount>0) OR
         (price_kind='ton' AND price_amount>0 AND price_nanos=0)) AND
        schedule_date>=0 AND
        (state IN ('balance_low','rejected') OR schedule_date>0) AND
        approval_service_message_id>=0 AND published_message_id>=0 AND
        settlement_due>=0 AND final_service_message_id>=0
    );

-- === from 0126_star_gift_user_refs_and_profile_state.up.sql ===
-- Official clients may continue lifecycle actions from a freshly emitted
-- messageActionStarGiftUnique. Keep those user-local message ids as explicit
-- durable references to the same saved gift aggregate.
CREATE TABLE IF NOT EXISTS star_gift_user_message_refs (
    owner_user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    msg_id integer NOT NULL,
    saved_gift_id bigint NOT NULL REFERENCES peer_star_gifts(id) ON DELETE CASCADE,
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (owner_user_id, msg_id),
    CONSTRAINT star_gift_user_message_refs_msg_check CHECK (owner_user_id > 0 AND msg_id > 0)
);

CREATE INDEX IF NOT EXISTS star_gift_user_message_refs_saved_idx
    ON star_gift_user_message_refs(saved_gift_id, owner_user_id, msg_id);

INSERT INTO star_gift_user_message_refs(owner_user_id,msg_id,saved_gift_id)
SELECT box.owner_user_id, box.box_id, gift.id
FROM message_boxes box
JOIN unique_star_gifts unique_gift
  ON (box.media #>> '{service_action,star_gift_unique,gift,ID}') ~ '^[0-9]+$'
 AND unique_gift.id = (box.media #>> '{service_action,star_gift_unique,gift,ID}')::bigint
JOIN peer_star_gifts gift
  ON gift.id = unique_gift.source_saved_gift_id
 AND gift.owner_peer_type = 'user'
 AND gift.owner_peer_id = box.owner_user_id
WHERE NOT box.deleted
  AND box.media #>> '{service_action,kind}' = 'star_gift_unique'
  AND box.box_id <> gift.msg_id;

-- Hidden gifts cannot remain pinned. Compacting the whole owner vector here
-- also repairs historical gaps before the invariant is constrained.
ALTER TABLE peer_star_gifts
    DROP CONSTRAINT IF EXISTS peer_star_gifts_hidden_unpinned_check;
ALTER TABLE peer_star_gifts
    ADD CONSTRAINT peer_star_gifts_hidden_unpinned_check
    CHECK (pinned_order<=6 AND (NOT unsaved OR pinned_order=0)) NOT VALID;

-- Compact pin order without TEMP ON COMMIT DROP (migrate may commit statement-wise
-- in some drivers; CTE keeps the snapshot and write in one statement).
WITH ranked AS (
    SELECT id,
           row_number() OVER (
               PARTITION BY owner_peer_type, owner_peer_id
               ORDER BY pinned_order, id
           )::integer AS new_order
    FROM peer_star_gifts
    WHERE lifecycle_status = 'active' AND NOT unsaved AND pinned_order > 0
),
capped AS (
    SELECT id, new_order FROM ranked WHERE new_order <= 6
)
UPDATE peer_star_gifts g
SET pinned_order = COALESCE((SELECT c.new_order FROM capped c WHERE c.id = g.id), 0)
WHERE g.pinned_order <> 0
   OR EXISTS (SELECT 1 FROM capped c WHERE c.id = g.id);

-- peer and saved_id share one TL flag and are channel-only. Earlier user gift
-- projections set peer=user (and sometimes a user box id in saved_id), which
-- made TDesktop select zero/stale ids instead of the emitted service message.
CREATE TEMP TABLE star_gift_user_unique_media_repairs (
    owner_user_id bigint NOT NULL,
    box_id integer NOT NULL,
    peer_type text NOT NULL,
    peer_id bigint NOT NULL,
    repaired_media jsonb NOT NULL,
    PRIMARY KEY(owner_user_id,box_id)
);

INSERT INTO star_gift_user_unique_media_repairs(owner_user_id,box_id,peer_type,peer_id,repaired_media)
SELECT box.owner_user_id,
       box.box_id,
       box.peer_type,
       box.peer_id,
       jsonb_set(
           box.media #- '{service_action,star_gift_unique,saved_id}',
           '{service_action,star_gift_unique,peer}',
           '{"ID":0,"Type":""}'::jsonb,
           true
       )
FROM message_boxes box
WHERE NOT box.deleted
  AND box.media #>> '{service_action,kind}' = 'star_gift_unique'
  AND box.media #>> '{service_action,star_gift_unique,peer,Type}' = 'user';

DO $$
DECLARE
    repair record;
    next_pts integer;
    event_date integer := EXTRACT(EPOCH FROM clock_timestamp())::integer;
BEGIN
    FOR repair IN
        SELECT owner_user_id,box_id,peer_type,peer_id,repaired_media
        FROM star_gift_user_unique_media_repairs
        ORDER BY owner_user_id,box_id
    LOOP
        INSERT INTO user_update_watermarks(user_id,contiguous_pts)
        VALUES(repair.owner_user_id,0)
        ON CONFLICT(user_id) DO NOTHING;

        UPDATE user_update_watermarks
        SET contiguous_pts=contiguous_pts+1,updated_at=now()
        WHERE user_id=repair.owner_user_id
        RETURNING contiguous_pts INTO next_pts;

        UPDATE message_boxes
        SET media=repair.repaired_media,pts=next_pts
        WHERE owner_user_id=repair.owner_user_id AND box_id=repair.box_id AND NOT deleted;

        INSERT INTO user_update_events(
            user_id,pts,pts_count,date,event_type,message_box_id,peer_type,peer_id
        ) VALUES(
            repair.owner_user_id,next_pts,1,event_date,'edit_message',repair.box_id,repair.peer_type,repair.peer_id
        );

        INSERT INTO dispatch_outbox(
            target_user_id,pts,event_type,exclude_auth_key_id,exclude_session_id
        ) VALUES(repair.owner_user_id,next_pts,'edit_message',0,0);
    END LOOP;
END
$$;

UPDATE private_messages
SET media=jsonb_set(
    media #- '{service_action,star_gift_unique,saved_id}',
    '{service_action,star_gift_unique,peer}',
    '{"ID":0,"Type":""}'::jsonb,
    true
)
WHERE media #>> '{service_action,kind}' = 'star_gift_unique'
  AND media #>> '{service_action,star_gift_unique,peer,Type}' = 'user';

DROP TABLE IF EXISTS star_gift_user_unique_media_repairs;

-- === from 0150_channel_star_gift_notifications.up.sql ===
-- Channel gift purchases commit a durable recipient snapshot before any
-- private notification is attempted. Delivery is idempotent and restart-safe:
-- the deterministic private-send replay is authoritative if a process stops
-- after writing the message but before marking this job delivered.
CREATE TABLE IF NOT EXISTS star_gift_channel_notification_jobs (
    saved_gift_id bigint NOT NULL REFERENCES peer_star_gifts(id) ON DELETE CASCADE,
    target_user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    gift_date integer NOT NULL,
    action jsonb NOT NULL,
    attempts integer NOT NULL DEFAULT 0,
    next_attempt_at integer NOT NULL,
    lease_until integer NOT NULL DEFAULT 0,
    delivered_at integer NOT NULL DEFAULT 0,
    message_id integer NOT NULL DEFAULT 0,
    last_error text NOT NULL DEFAULT '',
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (saved_gift_id, target_user_id),
    CONSTRAINT star_gift_channel_notification_jobs_state_check CHECK (
        saved_gift_id > 0
        AND target_user_id > 0
        AND gift_date > 0
        AND attempts >= 0
        AND next_attempt_at > 0
        AND lease_until >= 0
        AND delivered_at >= 0
        AND message_id >= 0
        AND ((delivered_at = 0 AND message_id = 0) OR (delivered_at > 0 AND message_id > 0))
    )
);

CREATE INDEX IF NOT EXISTS star_gift_channel_notification_jobs_pending_idx
    ON star_gift_channel_notification_jobs(next_attempt_at, lease_until, saved_gift_id, target_user_id)
    WHERE delivered_at = 0;

COMMENT ON TABLE star_gift_channel_notification_jobs IS
    'Purchase-time snapshot of per-admin channel gift notification intents; delivery uses deterministic private-message replay.';

COMMENT ON TABLE star_gift_user_message_refs IS
    'Viewer-local private service-message aliases to saved gift aggregates; the saved gift owner may be that user or an authorized channel.';

-- Existing deployments/users already have channel prepaid/upgrade notifications.
-- Backfill only aliases that are cryptographically unnecessary to guess: the
-- persisted action itself names a channel and saved_id, and that exact pair
-- must resolve to one saved gift. This changes no message, PTS or outbox row.
WITH ordinary AS (
    SELECT box.owner_user_id,
           box.box_id,
           gift.id AS saved_gift_id
    FROM message_boxes box
    JOIN peer_star_gifts gift
      ON gift.owner_peer_type = 'channel'
     AND (box.media #>> '{service_action,star_gift,peer_channel_id}') ~ '^[1-9][0-9]*$'
     AND gift.owner_peer_id = (box.media #>> '{service_action,star_gift,peer_channel_id}')::bigint
     AND (box.media #>> '{service_action,star_gift,saved_id}') ~ '^[1-9][0-9]*$'
     AND gift.saved_id = (box.media #>> '{service_action,star_gift,saved_id}')::bigint
    WHERE NOT box.deleted
      AND box.media #>> '{service_action,kind}' = 'star_gift'
      AND gift.lifecycle_status = 'active'
), collectible AS (
    SELECT box.owner_user_id,
           box.box_id,
           gift.id AS saved_gift_id
    FROM message_boxes box
    JOIN peer_star_gifts gift
      ON gift.owner_peer_type = 'channel'
     AND box.media #>> '{service_action,star_gift_unique,peer,Type}' = 'channel'
     AND (box.media #>> '{service_action,star_gift_unique,peer,ID}') ~ '^[1-9][0-9]*$'
     AND gift.owner_peer_id = (box.media #>> '{service_action,star_gift_unique,peer,ID}')::bigint
     AND (box.media #>> '{service_action,star_gift_unique,saved_id}') ~ '^[1-9][0-9]*$'
     AND gift.saved_id = (box.media #>> '{service_action,star_gift_unique,saved_id}')::bigint
     AND (box.media #>> '{service_action,star_gift_unique,gift,ID}') ~ '^[1-9][0-9]*$'
     AND gift.unique_gift_id = (box.media #>> '{service_action,star_gift_unique,gift,ID}')::bigint
    WHERE NOT box.deleted
      AND box.media #>> '{service_action,kind}' = 'star_gift_unique'
      AND gift.lifecycle_status = 'active'
), aliases AS (
    SELECT * FROM ordinary
    UNION
    SELECT * FROM collectible
)
INSERT INTO star_gift_user_message_refs(owner_user_id, msg_id, saved_gift_id)
SELECT owner_user_id, box_id, saved_gift_id
FROM aliases
ON CONFLICT(owner_user_id, msg_id) DO UPDATE
SET saved_gift_id = EXCLUDED.saved_gift_id
WHERE star_gift_user_message_refs.saved_gift_id = EXCLUDED.saved_gift_id;

