-- Bridge upstream gramsrv 0167-0174 for databases that already reached
-- timestamp migrations (>= 20260714003099) before those sequential files
-- landed in this fork. Fresh installs apply 0167-0174 directly.

-- === 0167 premium_stars ===
DO $m0167$
BEGIN
    IF to_regclass('public.premium_plans') IS NOT NULL THEN
        RETURN;
    END IF;

    ALTER TABLE public.users
        ADD COLUMN IF NOT EXISTS premium_updated_at timestamp with time zone;

    ALTER TABLE public.account_settings
        ADD COLUMN IF NOT EXISTS disallow_unlimited_stargifts boolean DEFAULT false NOT NULL,
        ADD COLUMN IF NOT EXISTS disallow_limited_stargifts boolean DEFAULT false NOT NULL,
        ADD COLUMN IF NOT EXISTS disallow_unique_stargifts boolean DEFAULT false NOT NULL,
        ADD COLUMN IF NOT EXISTS disallow_premium_gifts boolean DEFAULT false NOT NULL,
        ADD COLUMN IF NOT EXISTS disallow_stargifts_from_channels boolean DEFAULT false NOT NULL;

    CREATE TABLE public.premium_plans (
        months integer NOT NULL,
        duration_days integer NOT NULL,
        amount_stars bigint NOT NULL,
        enabled boolean DEFAULT true NOT NULL,
        sort_order integer DEFAULT 0 NOT NULL,
        label text NOT NULL,
        version bigint DEFAULT 1 NOT NULL,
        updated_at timestamp with time zone DEFAULT now() NOT NULL,
        CONSTRAINT premium_plans_pkey PRIMARY KEY (months),
        CONSTRAINT premium_plans_months_valid CHECK (months > 0 AND months <= 120),
        CONSTRAINT premium_plans_duration_valid CHECK (duration_days > 0 AND duration_days <= 36500),
        CONSTRAINT premium_plans_amount_valid CHECK (amount_stars > 0 AND amount_stars <= 1000000000000000),
        CONSTRAINT premium_plans_version_positive CHECK (version > 0),
        CONSTRAINT premium_plans_label_nonempty CHECK (label <> '')
    );

    INSERT INTO public.premium_plans
        (months, duration_days, amount_stars, enabled, sort_order, label, version)
    VALUES
        (3, 90, 750, true, 10, '3 months', 1),
        (6, 180, 1300, true, 20, '6 months', 1),
        (12, 365, 2400, true, 30, '12 months', 1)
    ON CONFLICT (months) DO NOTHING;

    CREATE TABLE public.premium_payment_intents (
        id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        form_id bigint NOT NULL,
        idempotency_key text NOT NULL,
        buyer_user_id bigint NOT NULL,
        purchase_kind text NOT NULL,
        recipient_user_id bigint NOT NULL,
        months integer NOT NULL,
        duration_days integer NOT NULL,
        amount_stars bigint NOT NULL,
        currency text DEFAULT 'XTR' NOT NULL,
        plan_version bigint NOT NULL,
        gift_message text DEFAULT '' NOT NULL,
        gift_entities jsonb DEFAULT '[]'::jsonb NOT NULL,
        status text DEFAULT 'pending' NOT NULL,
        issued_at timestamp with time zone NOT NULL,
        expires_at timestamp with time zone NOT NULL,
        paid_at timestamp with time zone,
        refunded_at timestamp with time zone,
        stars_transaction_id bigint,
        sender_message_id integer,
        recipient_message_id integer,
        created_at timestamp with time zone DEFAULT now() NOT NULL,
        updated_at timestamp with time zone DEFAULT now() NOT NULL,
        CONSTRAINT premium_payment_intents_pkey PRIMARY KEY (id),
        CONSTRAINT premium_payment_intents_form_unique UNIQUE (form_id),
        CONSTRAINT premium_payment_intents_idempotency_unique UNIQUE (idempotency_key),
        CONSTRAINT premium_payment_intents_idempotency_valid
            CHECK (idempotency_key <> '' AND octet_length(idempotency_key) <= 256),
        CONSTRAINT premium_payment_intents_kind_valid CHECK (purchase_kind IN ('self', 'gift')),
        CONSTRAINT premium_payment_intents_status_valid
            CHECK (status IN ('pending', 'processing', 'paid', 'failed', 'expired', 'refunded')),
        CONSTRAINT premium_payment_intents_currency_xtr CHECK (currency = 'XTR'),
        CONSTRAINT premium_payment_intents_amount_valid
            CHECK (amount_stars > 0 AND amount_stars <= 1000000000000000),
        CONSTRAINT premium_payment_intents_duration_valid
            CHECK (months > 0 AND months <= 120 AND duration_days > 0 AND duration_days <= 36500),
        CONSTRAINT premium_payment_intents_plan_version_positive CHECK (plan_version > 0),
        CONSTRAINT premium_payment_intents_gift_message_valid
            CHECK (char_length(gift_message) <= 128),
        CONSTRAINT premium_payment_intents_gift_entities_valid
            CHECK (CASE WHEN jsonb_typeof(gift_entities) = 'array'
                THEN jsonb_array_length(gift_entities) <= 100 ELSE false END),
        CONSTRAINT premium_payment_intents_form_positive CHECK (form_id > 0),
        CONSTRAINT premium_payment_intents_window_valid CHECK (expires_at > issued_at),
        CONSTRAINT premium_payment_intents_buyer_fkey FOREIGN KEY (buyer_user_id)
            REFERENCES public.users(id) ON DELETE RESTRICT,
        CONSTRAINT premium_payment_intents_recipient_fkey FOREIGN KEY (recipient_user_id)
            REFERENCES public.users(id) ON DELETE RESTRICT
    );

    CREATE UNIQUE INDEX IF NOT EXISTS premium_payment_intents_buyer_form_idx
        ON public.premium_payment_intents (buyer_user_id, form_id);
    CREATE INDEX IF NOT EXISTS premium_payment_intents_status_expires_idx
        ON public.premium_payment_intents (status, expires_at);
    CREATE INDEX IF NOT EXISTS premium_payment_intents_recipient_idx
        ON public.premium_payment_intents (recipient_user_id, id DESC);
    CREATE UNIQUE INDEX IF NOT EXISTS premium_payment_intents_transaction_unique
        ON public.premium_payment_intents (stars_transaction_id)
        WHERE stars_transaction_id IS NOT NULL;

    CREATE TABLE public.premium_entitlements (
        id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        user_id bigint NOT NULL,
        source text NOT NULL,
        source_user_id bigint DEFAULT 0 NOT NULL,
        payment_intent_id bigint,
        transaction_id bigint,
        months integer NOT NULL,
        duration_days integer NOT NULL,
        starts_at timestamp with time zone NOT NULL,
        expires_at timestamp with time zone NOT NULL,
        status text DEFAULT 'active' NOT NULL,
        command_key text DEFAULT '' NOT NULL,
        revoked_at timestamp with time zone,
        refunded_at timestamp with time zone,
        reason text DEFAULT '' NOT NULL,
        metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
        created_at timestamp with time zone DEFAULT now() NOT NULL,
        updated_at timestamp with time zone DEFAULT now() NOT NULL,
        CONSTRAINT premium_entitlements_pkey PRIMARY KEY (id),
        CONSTRAINT premium_entitlements_source_valid CHECK (source IN ('purchase', 'gift', 'gift_code', 'admin', 'promo')),
        CONSTRAINT premium_entitlements_status_valid CHECK (status IN ('active', 'expired', 'revoked', 'refunded')),
        CONSTRAINT premium_entitlements_duration_valid
            CHECK (months > 0 AND months <= 120 AND duration_days > 0 AND duration_days <= 36500),
        CONSTRAINT premium_entitlements_command_key_valid CHECK (octet_length(command_key) <= 256),
        CONSTRAINT premium_entitlements_window_valid CHECK (expires_at > starts_at),
        CONSTRAINT premium_entitlements_user_fkey FOREIGN KEY (user_id)
            REFERENCES public.users(id) ON DELETE RESTRICT,
        CONSTRAINT premium_entitlements_payment_fkey FOREIGN KEY (payment_intent_id)
            REFERENCES public.premium_payment_intents(id) ON DELETE RESTRICT,
        CONSTRAINT premium_entitlements_transaction_fkey FOREIGN KEY (transaction_id)
            REFERENCES public.stars_transactions(id) ON DELETE RESTRICT
    );

    CREATE UNIQUE INDEX IF NOT EXISTS premium_entitlements_payment_unique
        ON public.premium_entitlements (payment_intent_id)
        WHERE payment_intent_id IS NOT NULL;
    CREATE UNIQUE INDEX IF NOT EXISTS premium_entitlements_transaction_unique
        ON public.premium_entitlements (transaction_id)
        WHERE transaction_id IS NOT NULL;
    CREATE UNIQUE INDEX IF NOT EXISTS premium_entitlements_admin_command_unique
        ON public.premium_entitlements (source, source_user_id, command_key)
        WHERE command_key <> '';
    CREATE INDEX IF NOT EXISTS premium_entitlements_user_expires_idx
        ON public.premium_entitlements (user_id, expires_at DESC);
    CREATE INDEX IF NOT EXISTS premium_entitlements_active_expires_idx
        ON public.premium_entitlements (expires_at, user_id)
        WHERE status = 'active';
    CREATE INDEX IF NOT EXISTS premium_entitlements_status_idx
        ON public.premium_entitlements (status, id DESC);

    CREATE TABLE public.premium_audit_events (
        id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        actor_user_id bigint DEFAULT 0 NOT NULL,
        target_user_id bigint NOT NULL,
        payment_intent_id bigint,
        entitlement_id bigint,
        action text NOT NULL,
        command_key text DEFAULT '' NOT NULL,
        reason text DEFAULT '' NOT NULL,
        metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
        created_at timestamp with time zone DEFAULT now() NOT NULL,
        CONSTRAINT premium_audit_events_pkey PRIMARY KEY (id),
        CONSTRAINT premium_audit_events_action_nonempty CHECK (action <> '')
    );

    CREATE INDEX IF NOT EXISTS premium_audit_events_target_idx
        ON public.premium_audit_events (target_user_id, id DESC);
    CREATE INDEX IF NOT EXISTS premium_audit_events_payment_idx
        ON public.premium_audit_events (payment_intent_id, id DESC)
        WHERE payment_intent_id IS NOT NULL;
    CREATE UNIQUE INDEX IF NOT EXISTS premium_audit_events_command_unique
        ON public.premium_audit_events (actor_user_id, action, command_key)
        WHERE command_key <> '';

    ALTER TABLE public.stars_transactions
        ADD COLUMN IF NOT EXISTS premium_payment_intent_id bigint,
        ADD COLUMN IF NOT EXISTS premium_recipient_user_id bigint,
        ADD COLUMN IF NOT EXISTS premium_months integer;

    CREATE UNIQUE INDEX IF NOT EXISTS stars_transactions_premium_payment_unique
        ON public.stars_transactions (premium_payment_intent_id)
        WHERE premium_payment_intent_id IS NOT NULL;

    INSERT INTO public.users (
        id, access_hash, phone, first_name, last_name, username, country_code,
        created_at, updated_at, verified, support, about, last_seen_at,
        default_history_ttl_period, is_bot, bot_info_version, premium_expires_at,
        emoji_status_document_id, emoji_status_until, color_set, color,
        color_background_emoji_id, profile_color_set, profile_color,
        profile_color_background_emoji_id
    ) VALUES (
        1250000015, 5841763291047652381, '', 'Premium Bot', '', 'premiumbot', '',
        now(), now(), true, false,
        'Покупка Premium для себя или в подарок за Telegram Stars.',
        0, 0, true, 1, NULL, 0, 0, false, 0, 0, false, 0, 0
    )
    ON CONFLICT (id) DO UPDATE SET
        access_hash = EXCLUDED.access_hash,
        first_name = EXCLUDED.first_name,
        username = EXCLUDED.username,
        verified = EXCLUDED.verified,
        about = EXCLUDED.about,
        is_bot = EXCLUDED.is_bot,
        bot_info_version = GREATEST(public.users.bot_info_version, EXCLUDED.bot_info_version),
        updated_at = now();

    INSERT INTO public.bots (
        bot_user_id, owner_user_id, token_secret, description, commands,
        bot_chat_history, bot_nochats, inline_placeholder, created_at, updated_at,
        menu_button_type, menu_button_text, menu_button_url, bot_inline_geo
    ) VALUES (
        1250000015, 1250000015, '',
        'Покупка Premium для себя или в подарок. Все цены указаны в Telegram Stars.',
        '[
            {"command": "start", "description": "открыть магазин Premium"},
            {"command": "premium", "description": "купить Premium для себя"},
            {"command": "gift", "description": "подарить Premium пользователю"},
            {"command": "status", "description": "проверить статус Premium"},
            {"command": "history", "description": "показать историю покупок"},
            {"command": "terms", "description": "показать условия покупки"},
            {"command": "help", "description": "показать справку"}
        ]'::jsonb,
        false, true, '', now(), now(), 0, '', '', false
    )
    ON CONFLICT (bot_user_id) DO UPDATE SET
        owner_user_id = EXCLUDED.owner_user_id,
        description = EXCLUDED.description,
        commands = EXCLUDED.commands,
        updated_at = now();

    INSERT INTO public.peer_usernames (
        username_lower, username, peer_type, peer_id, active, editable, sort_order, updated_at
    )
    VALUES ('premiumbot', 'premiumbot', 'user', 1250000015, true, false, 0, now())
    ON CONFLICT (username_lower) DO NOTHING;

    INSERT INTO public.read_model_versions (model, owner_user_id, peer_type, peer_id, version, updated_at, hash)
    VALUES
        ('contact_account', 1250000015, 'user', 1250000015, 1, now(), 2500001500001),
        ('channel_active_memberships', 1250000015, 'user', 1250000015, 1, now(), 2500001500002)
    ON CONFLICT (model, owner_user_id, peer_type, peer_id) DO UPDATE SET
        version = GREATEST(public.read_model_versions.version, EXCLUDED.version),
        updated_at = now(),
        hash = EXCLUDED.hash;
END
$m0167$;

-- === 0168 premium_plan_management ===
ALTER TABLE public.premium_plans
    ADD COLUMN IF NOT EXISTS managed_by text DEFAULT 'config' NOT NULL;

DO $m0168$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'premium_plans_managed_by_valid'
          AND conrelid = 'public.premium_plans'::regclass
    ) THEN
        ALTER TABLE public.premium_plans
            ADD CONSTRAINT premium_plans_managed_by_valid
                CHECK (managed_by IN ('config', 'admin'));
    END IF;
END
$m0168$;

-- === 0169 premium_native_checkout ===
DO $m0169$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = 'premium_plans' AND column_name = 'fiat_currency'
    ) THEN
        ALTER TABLE public.premium_plans
            ADD COLUMN fiat_currency text DEFAULT 'USD' NOT NULL,
            ADD COLUMN fiat_amount bigint DEFAULT 1 NOT NULL,
            ADD COLUMN store_product text DEFAULT '' NOT NULL,
            ADD COLUMN store_quantity integer DEFAULT 0 NOT NULL;

        UPDATE public.premium_plans SET fiat_amount = amount_stars;

        ALTER TABLE public.premium_plans
            ADD CONSTRAINT premium_plans_fiat_currency_valid
                CHECK (fiat_currency ~ '^[A-Z]{3}$'),
            ADD CONSTRAINT premium_plans_fiat_amount_valid
                CHECK (fiat_amount > 0 AND fiat_amount <= 1000000000000000),
            ADD CONSTRAINT premium_plans_store_product_valid
                CHECK (octet_length(store_product) <= 256),
            ADD CONSTRAINT premium_plans_store_quantity_valid
                CHECK ((store_product = '' AND store_quantity = 0) OR
                       (store_product <> '' AND store_quantity > 0));
    END IF;

    IF to_regclass('public.premium_payment_intents') IS NOT NULL
       AND NOT EXISTS (
           SELECT 1 FROM information_schema.columns
           WHERE table_schema = 'public' AND table_name = 'premium_payment_intents' AND column_name = 'payment_amount'
       ) THEN
        ALTER TABLE public.premium_payment_intents
            DROP CONSTRAINT IF EXISTS premium_payment_intents_currency_xtr,
            ADD COLUMN payment_amount bigint DEFAULT 1 NOT NULL,
            ADD COLUMN debit_stars boolean DEFAULT true NOT NULL;

        UPDATE public.premium_payment_intents SET payment_amount = amount_stars;

        ALTER TABLE public.premium_payment_intents
            ADD CONSTRAINT premium_payment_intents_currency_valid
                CHECK (currency ~ '^[A-Z]{3}$'),
            ADD CONSTRAINT premium_payment_intents_payment_amount_valid
                CHECK (payment_amount > 0 AND payment_amount <= 1000000000000000),
            ADD CONSTRAINT premium_payment_intents_checkout_rail_valid
                CHECK ((debit_stars AND currency = 'XTR') OR
                       (NOT debit_stars AND currency <> 'XTR'));
    END IF;
END
$m0169$;

-- === 0170 official_star_gift_unlimited_supply (data repair; safe to re-run) ===
DO $m0170$
BEGIN
    IF to_regclass('public.star_gift_collectible_revisions') IS NULL THEN
        RETURN;
    END IF;
    ALTER TABLE public.star_gift_collectible_revisions
        DISABLE TRIGGER star_gift_collectible_revision_guard;

    UPDATE public.star_gift_collectible_revisions collectible
    SET supply_total = catalog_revision.upgrade_variants
    FROM public.star_gift_catalog catalog
    JOIN public.star_gift_catalog_revisions catalog_revision
      ON catalog_revision.id = catalog.active_revision_id
    WHERE catalog.collectible_revision_id = collectible.id
      AND collectible.status = 'published'
      AND collectible.official_gift_id IS NOT NULL
      AND catalog_revision.official_gift_id = collectible.official_gift_id
      AND NOT catalog_revision.limited
      AND catalog_revision.availability_total = 0
      AND catalog_revision.upgrade_variants > 1
      AND collectible.supply_total = 1;

    ALTER TABLE public.star_gift_collectible_revisions
        ENABLE TRIGGER star_gift_collectible_revision_guard;

    UPDATE public.star_gift_catalog catalog
    SET updated_at = now()
    FROM public.star_gift_catalog_revisions catalog_revision,
         public.star_gift_collectible_revisions collectible
    WHERE catalog_revision.id = catalog.active_revision_id
      AND collectible.id = catalog.collectible_revision_id
      AND collectible.status = 'published'
      AND collectible.official_gift_id IS NOT NULL
      AND catalog_revision.official_gift_id = collectible.official_gift_id
      AND NOT catalog_revision.limited
      AND catalog_revision.availability_total = 0
      AND catalog_revision.upgrade_variants > 1
      AND collectible.supply_total = catalog_revision.upgrade_variants;
END
$m0170$;

-- === 0171 collectible_phones ===
DO $m0171$
BEGIN
    IF to_regclass('public.collectible_phones') IS NOT NULL THEN
        RETURN;
    END IF;

    CREATE TABLE public.collectible_phones (
        id bigserial PRIMARY KEY,
        phone text NOT NULL CHECK (phone ~ '^888[0-9]{4,12}$'),
        tier text NOT NULL CHECK (tier IN ('standard', 'exclusive')),
        status text NOT NULL CHECK (status IN ('vault', 'owned', 'burned')),
        owner_user_id bigint NOT NULL DEFAULT 0 CHECK (owner_user_id >= 0),
        CHECK ((status = 'owned' AND owner_user_id > 0) OR (status <> 'owned' AND owner_user_id = 0)),
        purchase_date timestamptz NOT NULL,
        currency text NOT NULL CHECK (currency IN ('XTR', 'TON', 'USD')),
        amount bigint NOT NULL CHECK (amount >= 0),
        crypto_currency text NOT NULL DEFAULT '' CHECK (crypto_currency IN ('', 'TON')),
        crypto_amount bigint NOT NULL DEFAULT 0 CHECK (crypto_amount >= 0),
        CHECK ((crypto_currency = '' AND crypto_amount = 0) OR (crypto_currency = 'TON' AND crypto_amount > 0)),
        url text NOT NULL DEFAULT '' CHECK (octet_length(url) <= 512),
        original_owner_user_id bigint NOT NULL DEFAULT 0 CHECK (original_owner_user_id >= 0),
        transfer_count integer NOT NULL DEFAULT 0 CHECK (transfer_count >= 0),
        version bigint NOT NULL DEFAULT 1 CHECK (version > 0),
        created_at timestamptz NOT NULL,
        updated_at timestamptz NOT NULL CHECK (updated_at >= created_at)
    );

    CREATE UNIQUE INDEX collectible_phones_live_phone_idx ON public.collectible_phones(phone) WHERE status <> 'burned';
    CREATE UNIQUE INDEX collectible_phones_owned_user_idx ON public.collectible_phones(owner_user_id) WHERE status = 'owned';
    CREATE INDEX collectible_phones_status_tier_idx ON public.collectible_phones(status, tier, id DESC);

    CREATE TABLE public.collectible_phone_transfers (
        id bigserial PRIMARY KEY,
        collectible_id bigint NOT NULL REFERENCES public.collectible_phones(id) ON DELETE CASCADE,
        kind text NOT NULL CHECK (kind IN ('mint', 'transfer', 'revoke', 'burn')),
        from_user_id bigint NOT NULL DEFAULT 0 CHECK (from_user_id >= 0),
        to_user_id bigint NOT NULL DEFAULT 0 CHECK (to_user_id >= 0),
        currency text NOT NULL DEFAULT '' CHECK (currency IN ('', 'XTR', 'TON', 'USD')),
        amount bigint NOT NULL DEFAULT 0 CHECK (amount >= 0),
        actor text NOT NULL DEFAULT '' CHECK (octet_length(actor) <= 128),
        reason text NOT NULL DEFAULT '' CHECK (octet_length(reason) <= 512),
        command_key text CHECK (command_key IS NULL OR octet_length(command_key) BETWEEN 1 AND 128),
        created_at timestamptz NOT NULL
    );
    CREATE UNIQUE INDEX collectible_phone_transfers_command_idx ON public.collectible_phone_transfers(command_key) WHERE command_key IS NOT NULL;
    CREATE INDEX collectible_phone_transfers_asset_idx ON public.collectible_phone_transfers(collectible_id, id DESC);

    CREATE OR REPLACE FUNCTION public.release_deleted_user_collectible_phone() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      UPDATE public.collectible_phones SET status='vault', owner_user_id=0, version=version+1, updated_at=now()
      WHERE status='owned' AND owner_user_id=OLD.id;
      RETURN OLD;
    END;
    $$;
    DROP TRIGGER IF EXISTS users_release_collectible_phone ON public.users;
    CREATE TRIGGER users_release_collectible_phone BEFORE DELETE ON public.users
    FOR EACH ROW EXECUTE FUNCTION public.release_deleted_user_collectible_phone();
    CREATE OR REPLACE FUNCTION public.release_soft_deleted_user_collectible_phone() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      UPDATE public.collectible_phones SET status='vault', owner_user_id=0, version=version+1, updated_at=now()
      WHERE status='owned' AND owner_user_id=OLD.id;
      RETURN NEW;
    END;
    $$;
    DROP TRIGGER IF EXISTS users_release_collectible_phone_on_soft_delete ON public.users;
    CREATE TRIGGER users_release_collectible_phone_on_soft_delete BEFORE UPDATE OF deleted_at ON public.users
    FOR EACH ROW WHEN (OLD.deleted_at IS NULL AND NEW.deleted_at IS NOT NULL)
    EXECUTE FUNCTION public.release_soft_deleted_user_collectible_phone();
END
$m0171$;

-- === 0172 system_broadcasts ===
DO $m0172$
BEGIN
    IF to_regclass('public.broadcasts') IS NOT NULL THEN
        RETURN;
    END IF;

    CREATE TABLE broadcasts (
        id bigserial PRIMARY KEY,
        message text NOT NULL CHECK (message <> '' AND octet_length(message) <= 4096),
        target_mode varchar(16) NOT NULL CHECK (target_mode IN ('all', 'selected')),
        snapshot_max_user_id bigint NOT NULL DEFAULT 0,
        enumeration_cursor_user_id bigint NOT NULL DEFAULT 0,
        enumeration_done boolean NOT NULL DEFAULT false,
        target_count bigint NOT NULL DEFAULT 0 CHECK (target_count >= 0),
        materialized_count bigint NOT NULL DEFAULT 0 CHECK (materialized_count >= 0),
        sent_count bigint NOT NULL DEFAULT 0 CHECK (sent_count >= 0),
        failed_count bigint NOT NULL DEFAULT 0 CHECK (failed_count >= 0),
        created_by varchar(128) NOT NULL DEFAULT '',
        created_at timestamptz NOT NULL DEFAULT now(),
        CHECK (enumeration_cursor_user_id >= 0 AND enumeration_cursor_user_id <= snapshot_max_user_id),
        CHECK (sent_count + failed_count <= materialized_count)
    );

    CREATE TABLE broadcast_recipients (
        id bigserial PRIMARY KEY,
        broadcast_id bigint NOT NULL REFERENCES broadcasts(id) ON DELETE CASCADE,
        user_id bigint NOT NULL,
        status varchar(16) NOT NULL DEFAULT 'pending'
            CHECK (status IN ('pending', 'processing', 'sent', 'failed')),
        attempts integer NOT NULL DEFAULT 0 CHECK (attempts >= 0),
        next_attempt_at timestamptz NOT NULL DEFAULT now(),
        lease_token varchar(64) NOT NULL DEFAULT '',
        lease_until timestamptz,
        last_error varchar(500) NOT NULL DEFAULT '',
        private_message_id bigint NOT NULL DEFAULT 0,
        message_box_id integer NOT NULL DEFAULT 0,
        pts integer NOT NULL DEFAULT 0,
        sent_at timestamptz,
        created_at timestamptz NOT NULL DEFAULT now(),
        updated_at timestamptz NOT NULL DEFAULT now(),
        UNIQUE (broadcast_id, user_id),
        CHECK (
            (status = 'sent' AND private_message_id > 0 AND message_box_id > 0 AND pts > 0 AND sent_at IS NOT NULL)
            OR
            (status <> 'sent' AND private_message_id = 0 AND message_box_id = 0 AND pts = 0 AND sent_at IS NULL)
        ),
        CHECK (
            (status = 'processing' AND lease_token <> '' AND lease_until IS NOT NULL)
            OR
            (status <> 'processing' AND lease_token = '' AND lease_until IS NULL)
        )
    );

    CREATE INDEX broadcasts_enumeration_idx ON broadcasts (id)
        WHERE target_mode = 'all' AND NOT enumeration_done;
    CREATE INDEX broadcast_recipients_pending_idx ON broadcast_recipients (next_attempt_at, id)
        WHERE status = 'pending';
    CREATE INDEX broadcast_recipients_processing_idx ON broadcast_recipients (lease_until, id)
        WHERE status = 'processing';
    CREATE INDEX broadcast_recipients_broadcast_idx ON broadcast_recipients (broadcast_id, id);
END
$m0172$;

-- === 0173 gif_catalog ===
DO $m0173$
BEGIN
    IF to_regclass('public.gif_catalog') IS NOT NULL THEN
        RETURN;
    END IF;

    CREATE TABLE public.gif_catalog (
        id bigint NOT NULL,
        title text NOT NULL,
        document_id bigint NOT NULL REFERENCES public.documents(id),
        enabled boolean DEFAULT true NOT NULL,
        sort_order integer DEFAULT 0 NOT NULL,
        created_by text DEFAULT '' NOT NULL,
        source_filename text DEFAULT '' NOT NULL,
        source_sha256 text DEFAULT '' NOT NULL,
        created_at timestamp with time zone DEFAULT now() NOT NULL,
        updated_at timestamp with time zone DEFAULT now() NOT NULL,
        CONSTRAINT gif_catalog_pkey PRIMARY KEY (id),
        CONSTRAINT gif_catalog_title_valid CHECK (length(btrim(title)) BETWEEN 1 AND 128),
        CONSTRAINT gif_catalog_seed_pair CHECK ((source_filename = '') = (source_sha256 = '')),
        CONSTRAINT gif_catalog_sha256_valid CHECK (source_sha256 = '' OR source_sha256 ~ '^[0-9a-f]{64}$')
    );

    CREATE TABLE public.gif_catalog_capacity (
        singleton boolean PRIMARY KEY DEFAULT true,
        entry_count integer DEFAULT 0 NOT NULL,
        CONSTRAINT gif_catalog_capacity_singleton CHECK (singleton),
        CONSTRAINT gif_catalog_capacity_range CHECK (entry_count BETWEEN 0 AND 50)
    );

    INSERT INTO public.gif_catalog_capacity (singleton, entry_count) VALUES (true, 0);

    CREATE OR REPLACE FUNCTION public.reserve_gif_catalog_capacity() RETURNS trigger
        LANGUAGE plpgsql
    AS $$
    BEGIN
        UPDATE public.gif_catalog_capacity
        SET entry_count = entry_count + 1
        WHERE singleton AND entry_count < 50;
        IF NOT FOUND THEN
            RAISE EXCEPTION 'gif catalog is full'
                USING ERRCODE = '23514', CONSTRAINT = 'gif_catalog_capacity_limit';
        END IF;
        RETURN NEW;
    END;
    $$;

    CREATE OR REPLACE FUNCTION public.release_gif_catalog_capacity() RETURNS trigger
        LANGUAGE plpgsql
    AS $$
    BEGIN
        UPDATE public.gif_catalog_capacity
        SET entry_count = entry_count - 1
        WHERE singleton;
        RETURN OLD;
    END;
    $$;

    CREATE TRIGGER gif_catalog_reserve_capacity
        BEFORE INSERT ON public.gif_catalog
        FOR EACH ROW EXECUTE FUNCTION public.reserve_gif_catalog_capacity();

    CREATE TRIGGER gif_catalog_release_capacity
        AFTER DELETE ON public.gif_catalog
        FOR EACH ROW EXECUTE FUNCTION public.release_gif_catalog_capacity();

    CREATE UNIQUE INDEX gif_catalog_source_filename_unique
        ON public.gif_catalog (source_filename) WHERE source_filename <> '';
    CREATE UNIQUE INDEX gif_catalog_source_sha256_unique
        ON public.gif_catalog (source_sha256) WHERE source_sha256 <> '';
    CREATE UNIQUE INDEX gif_catalog_document_unique ON public.gif_catalog (document_id);
    CREATE INDEX gif_catalog_order_idx ON public.gif_catalog (sort_order, id);

    INSERT INTO public.users (
        id, access_hash, phone, first_name, last_name, username, country_code,
        created_at, updated_at, verified, support, about, last_seen_at,
        default_history_ttl_period, is_bot, bot_info_version, premium_expires_at,
        emoji_status_document_id, emoji_status_until, color_set, color,
        color_background_emoji_id, profile_color_set, profile_color,
        profile_color_background_emoji_id
    ) VALUES (
        1250000017, 7233282977235616768, '', 'GIF', '', 'gif', '',
        now(), now(), true, false, 'Search the server-curated GIF catalog.',
        0, 0, true, 1, NULL, 0, 0, false, 0, 0, false, 0, 0
    )
    ON CONFLICT (id) DO UPDATE SET
        access_hash=EXCLUDED.access_hash, first_name=EXCLUDED.first_name,
        username=EXCLUDED.username, verified=EXCLUDED.verified,
        about=EXCLUDED.about, is_bot=EXCLUDED.is_bot,
        bot_info_version=GREATEST(public.users.bot_info_version, EXCLUDED.bot_info_version),
        updated_at=now();

    INSERT INTO public.bots (
        bot_user_id, owner_user_id, token_secret, description, commands,
        bot_chat_history, bot_nochats, inline_placeholder, created_at, updated_at,
        menu_button_type, menu_button_text, menu_button_url, bot_inline_geo
    ) VALUES (
        1250000017, 1250000017, '', 'Search the server-curated GIF catalog.', '[]'::jsonb,
        false, true, 'Search GIFs', now(), now(), 0, '', '', false
    )
    ON CONFLICT (bot_user_id) DO UPDATE SET
        owner_user_id=EXCLUDED.owner_user_id, description=EXCLUDED.description,
        commands=EXCLUDED.commands, bot_chat_history=EXCLUDED.bot_chat_history,
        bot_nochats=EXCLUDED.bot_nochats, inline_placeholder=EXCLUDED.inline_placeholder,
        bot_inline_geo=EXCLUDED.bot_inline_geo, updated_at=now();

    INSERT INTO public.peer_usernames
        (username_lower, username, peer_type, peer_id, active, editable, sort_order, updated_at)
    VALUES ('gif', 'gif', 'user', 1250000017, true, false, 0, now())
    ON CONFLICT (username_lower) DO UPDATE SET
        username=EXCLUDED.username, peer_type=EXCLUDED.peer_type, peer_id=EXCLUDED.peer_id,
        active=EXCLUDED.active, editable=EXCLUDED.editable, updated_at=now();

    INSERT INTO public.read_model_versions (model, owner_user_id, peer_type, peer_id, version, updated_at, hash)
    VALUES
        ('contact_account', 1250000017, 'user', 1250000017, 1, now(), 2500001700001),
        ('channel_active_memberships', 1250000017, 'user', 1250000017, 1, now(), 2500001700002)
    ON CONFLICT (model, owner_user_id, peer_type, peer_id) DO UPDATE SET
        version=GREATEST(public.read_model_versions.version, EXCLUDED.version),
        updated_at=now(), hash=EXCLUDED.hash;
END
$m0173$;

-- === 0174 star_gift_message_entities ===
ALTER TABLE public.peer_star_gifts
    ADD COLUMN IF NOT EXISTS message_entities jsonb NOT NULL DEFAULT '[]'::jsonb;

ALTER TABLE public.star_gift_purchase_forms
    ADD COLUMN IF NOT EXISTS message_entities jsonb NOT NULL DEFAULT '[]'::jsonb;

DO $m0174$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'peer_star_gifts_message_entities_array_check'
          AND conrelid = 'public.peer_star_gifts'::regclass
    ) THEN
        ALTER TABLE public.peer_star_gifts
            ADD CONSTRAINT peer_star_gifts_message_entities_array_check
            CHECK (jsonb_typeof(message_entities) = 'array');
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'star_gift_purchase_forms_message_entities_array_check'
          AND conrelid = 'public.star_gift_purchase_forms'::regclass
    ) THEN
        ALTER TABLE public.star_gift_purchase_forms
            ADD CONSTRAINT star_gift_purchase_forms_message_entities_array_check
            CHECK (jsonb_typeof(message_entities) = 'array');
    END IF;
END
$m0174$;
